### ISSUE TITLE
Water Whip won't pickup on return

### ISSUE THREAD

**Issue by fluffyxox** [CAS-ual-TY/Spells-And-Shields#13]
Water whip won't catch the water in the bucket in ver 1.19.2-1.9.2

**Comment by CAS-ual-TY** [comment]
@fluffyxox Was the water bucket in your hand when the water returned?

**Comment by fluffyxox** [comment]
yes

**Comment by CAS-ual-TY** [comment]
Can not reproduce. Re-open when you can reproduce it reliably.

**Comment by CAS-ual-TY** [comment]
Nevermind, I was able to reproduce this bug and add a workaround. This issue is resolved now.
