### ISSUE TITLE
Cannot create the spells config file

### ISSUE THREAD

**Issue by Hiconel** [CAS-ual-TY/Spells-And-Shields#3]
I wanted to take a look at the json files for the spell trees and spells to maybe change some things, but they don't seem to generate. I activated both the trees as well as the spells in the common config, however only the trees appeared in their corresponding folder. Am I doing something wrong?
I tried it with a few earlier versions of the mod as well, but none seemed to create the files for the spells.

**Comment by CAS-ual-TY** [comment]
I need to see the common config

**Comment by Hiconel** [comment]
#Load spell trees from configuration files in the configuration folder (true) or use the default spell trees (false).
loadSpellTrees = false
#Create default spell tree configuration files in the configuration folder if said folder does not exist (true) or not (false).
createDefaultSpellTrees = false
#Add default mod spell trees to the game (true) or not (false).
addDefaultSpellTrees = true
#Load spell settings from existing configuration files in the configuration folder (true) or use the default settings (false).
loadSpells = false
#Create default spell configuration files in the configuration folder (true) or not (false).
createSpells = true
#Players respawn with their mana bar filled (true) or empty (false).
respawnWithFullMana = false
#Clear a player's spell slots on death (true) or not (false). If forgetSpellsOnDeath is set to true, this always behaves as if it was also set to true.
clearSlotsOnDeath = true
#Make a player forget all learned spells on death (true) or not (false). Forgotten spells are still visible in spell trees but must be relearned before you can equip them.
forgetSpellsOnDeath = true

**Comment by CAS-ual-TY** [comment]
Hi. loadSpellTrees must be set to true as well. This is unclear and will be changed in the future. Sorry for the delay.

**Comment by Hiconel** [comment]
Yes, it's working now! Thanks a lot for your help and sorry for not responding sooner. Also, great job with the mod so far and I am very excited the see where it's headed!

**Comment by CAS-ual-TY** [comment]
Reopening. Its still not clear. I need to change something.
