### ISSUE TITLE
Detrimental Issue with the Magic Shield Enchantment.

### ISSUE THREAD

**Issue by MEDiumdog337** [CAS-ual-TY/Spells-And-Shields#4]
Me and a few of my friends have downloaded the Spells-And-Shields mod. Everything was good up until we got the magic shield enchantment. It seemingly does nothing but I had recently found out that it will degrade your armor durability into the negitive values. It seems the enchantment is tied to getting experience orbs.

**Comment by CAS-ual-TY** [comment]
Thank you for the report. Which version are you playing on?

**Comment by CAS-ual-TY** [comment]
Since 63063fc2cb4070fa84301ed74f6df95ce546bad2 the enchantment now only goes on Shields

**Comment by MEDiumdog337** [comment]
1.19.1
