### ISSUE TITLE
Jeed mod compatibility

### ISSUE THREAD

**Issue by CCCClear** [CAS-ual-TY/Spells-And-Shields#6]
1.18.2 latest 
Currently the potion effects in this mod are not compatible with just enough effect description mod (a subsidiary mod of JEI) .
Therefore, the potion effect cannot be queried.

**Comment by CCCClear** [comment]
I've found that adding fields to the lang file solves this problem

**Comment by CAS-ual-TY** [comment]
Can you show me what you added?

**Comment by CCCClear** [comment]
Just like
"effect.spells_and_shields.extra_mana.description": "Provides additional mana. Additional mana is consumed first and does not regenerate";

**Comment by CAS-ual-TY** [comment]
Thank you! Will add that to the mod as well. Keeping it open until added.

**Comment by CCCClear** [comment]
By the way, compatibility with the Enchantment Description mod can be achieved in the same way, like this:
"enchantment.spells_and_shields.magic_protection.desc": "Similar to Protection, but protects twice as well against magic damage as the Protection",

**Comment by CAS-ual-TY** [comment]
I suspected this but did not look it up yet. Thank you for this! It will be included as well.

**Comment by CAS-ual-TY** [comment]
@CCCClear https://www.curseforge.com/minecraft/mc-mods/jei-enchantment-info this is the mod adding enchantment descriptions, correct?

**Comment by CAS-ual-TY** [comment]
Please let me know if this is correct (can close if yes): https://github.com/CAS-ual-TY/Spells-And-Shields/commit/50fca7c5344e1d4a5fbbf87b3aaddaef3330dd13#diff-9b6a23fe654d68dd73a43daad2c90c44ce17e2e0e5e8b640f8a778b87ebbbab3

**Comment by CCCClear** [comment]
Yes, I think that's correct.
But the enchantment descriptions mod I use is this one :
https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions
