### ISSUE TITLE
can't learn spells except water breathing minecraft 1.19

### ISSUE THREAD

**Issue by Vily118** [CAS-ual-TY/Spells-And-Shields#8]
Hello I cannot learn any other spells than water breathing even though i have enough xp
there is also another issue where the enchanting table seems to cap at level 1 enchants regardless the number of bookshelves, (it might not be link to the mod) here is the mod list.
![Capture d’écran 2022-09-26 193308](https://user-images.githubusercontent.com/114432328/192342858-e43406a8-791d-4b30-a796-6b267c1cc1c0.png)

**Comment by CAS-ual-TY** [comment]
Update to a newer version. Tell other mod authors to update. This has long been fixed.
