### ISSUE TITLE
Spit Metal doesn't use baseDamage

### ISSUE THREAD

**Issue by iddo1453** [CAS-ual-TY/Spells-And-Shields#9]
Using version 1.9 for 1.18.2.
Forge version 40.1.84
The spit metal spell seems to be dealing damage only based on the material's bonus damage (iron deals 2 damage and gold deals no damage). I tried both with loadSpells set to true and to false in the configs and got the same results.

**Comment by CAS-ual-TY** [comment]
Checked the code and can confirm. Will fix soon.
